language: python
python: 3.6
cache:
  directories:
    - $HOME/virtualenv/python3.6/

jobs:
  include:
    - stage: unit
      script: pytest tests/unit

    - stage: journey
      script: travis_wait 40 pytest tests/journey

    - stage: deploy
      script: skip
      deploy:
        provider: pypi
        user: serenata
        password: $PYPI_PASSWORD
        distributions: "sdist bdist_wheel"
        on:
          branch: master

install:
  - rm -rf .coverage
  - python -m pip install -e .
  - python -m pip install coveralls pytest pytest-cov==2.5.1

after_success:
  - coveralls
